# Generated by Django 5.1.2 on 2024-11-14 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0003_tagmodel_markmodel_postmodel_tags_storymodel_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='connected_users',
            field=models.ManyToManyField(related_name='connected_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
