# Generated by Django 5.1.2 on 2024-11-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
